#!/bin/bash

# Message function
msg () {
	echo "************ $1 ************"
}

# Dependencies
dependencies=""
dependencies+="git "
dependencies+="build-essential "

dependencies+="meson "
dependencies+="debhelper "
dependencies+="libgail-3-dev "
dependencies+="libnotify-dev "
dependencies+="libxt-dev "
dependencies+="libgtk-3-dev "
dependencies+="gtk-doc-tools "
dependencies+="libglib2.0-doc "
dependencies+="libgtk-3-doc "
dependencies+="libgirepository1.0-dev "
dependencies+="libxml2-dev "
dependencies+="libxapp-dev "
dependencies+="libexif-dev "
dependencies+="libexempi-dev "
dependencies+="ninja-build "
dependencies+="intltool "
dependencies+="libmate-desktop-dev "
dependencies+="libgdk-pixbuf2.0-dev"


if [ -f /etc/debian_version ]; then
	# Install dependencies for ubuntu based distributions
	msg "Installing dependencies"
	sudo apt install $dependencies
else
	msg "Debian based distribution not detected"
	msg "Please install the following packages:"
	msg "$dependencies"
fi
